import { and, eq, inArray } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/db/runtime";
import { approvals, auditEvents, jobs, observations, publicMarketReports, receipts, recipes, stockMovements, users } from "@/db/schema";
import { getAccessContext } from "@/lib/authorization";

const command = z.object({ userId: z.uuid(), action: z.enum(["quarantine", "unquarantine"]), reason: z.string().trim().min(3).max(1_000).optional() }).superRefine((value, ctx) => { if (value.action === "quarantine" && !value.reason) ctx.addIssue({ code: "custom", path: ["reason"], message: "A quarantine reason is required." }); });
export async function PATCH(request: NextRequest) { const context = await getAccessContext(); if (!context) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); if (context.globalRole !== "platform_admin") return NextResponse.json({ error: "platform_admin_required" }, { status: 403 }); const parsed = command.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "invalid_quarantine_command", issues: parsed.error.issues }, { status: 400 }); const input = parsed.data; const result = await db.transaction(async (tx) => { const [contributor] = await tx.select({ id: users.id, quarantinedAt: users.quarantinedAt }).from(users).where(eq(users.id, input.userId)).limit(1); if (!contributor) throw new Error("user_not_found"); if (input.action === "unquarantine") { await tx.update(users).set({ quarantinedAt: null, quarantineReason: null, updatedAt: new Date() }).where(eq(users.id, input.userId)); await tx.insert(jobs).values({ kind: "quarantine.recompute", payload: { userId: input.userId, action: "unquarantine", restoreHistoricalSignals: false } }); await tx.insert(auditEvents).values({ actorId: context.userId, action: "contributor.unquarantined", entityType: "user", entityId: input.userId }); return { action: input.action, rejectedReceipts: 0, quarantinedObservations: 0, historicalSignalsRestored: false }; }
    const now = new Date(); const pendingReceipts = await tx.select({ id: receipts.id, storeId: receipts.storeId }).from(receipts).where(and(eq(receipts.submittedBy, input.userId), eq(receipts.status, "pending"))); const pendingIds = pendingReceipts.map((row) => row.id); const provisional = pendingIds.length ? await tx.select().from(stockMovements).where(and(inArray(stockMovements.receiptId, pendingIds), eq(stockMovements.kind, "receipt"), eq(stockMovements.state, "provisional"))) : []; for (const movement of provisional) await tx.insert(stockMovements).values({ storeId: movement.storeId, itemId: movement.itemId, receiptId: movement.receiptId, kind: "rejection_reversal", state: "provisional", quantityDelta: -movement.quantityDelta, reason: `Contributor quarantine: ${input.reason}`, createdBy: context.userId }); if (pendingIds.length) { await tx.update(receipts).set({ status: "rejected", updatedAt: now }).where(inArray(receipts.id, pendingIds)); await tx.update(approvals).set({ decision: "rejected", reviewedBy: context.userId, reviewedAt: now, note: `Contributor quarantined: ${input.reason}` }).where(and(eq(approvals.targetType, "receipt"), inArray(approvals.targetId, pendingIds), eq(approvals.decision, "pending"))); }
    const pendingObservations = await tx.select({ id: observations.id }).from(observations).where(and(eq(observations.submittedBy, input.userId), eq(observations.approval, "pending"))); const observationIds = pendingObservations.map((row) => row.id); await tx.update(observations).set({ quarantinedAt: now, approval: "rejected" }).where(eq(observations.submittedBy, input.userId)); if (observationIds.length) await tx.update(approvals).set({ decision: "rejected", reviewedBy: context.userId, reviewedAt: now, note: `Contributor quarantined: ${input.reason}` }).where(and(eq(approvals.targetType, "observation"), inArray(approvals.targetId, observationIds), eq(approvals.decision, "pending")));
    const pendingRecipes = await tx.select({ id: recipes.id }).from(recipes).where(and(eq(recipes.submittedBy, input.userId), eq(recipes.approval, "pending"))); const recipeIds = pendingRecipes.map((row) => row.id); if (recipeIds.length) { await tx.update(recipes).set({ approval: "rejected" }).where(inArray(recipes.id, recipeIds)); await tx.update(approvals).set({ decision: "rejected", reviewedBy: context.userId, reviewedAt: now, note: `Contributor quarantined: ${input.reason}` }).where(and(eq(approvals.targetType, "recipe"), inArray(approvals.targetId, recipeIds), eq(approvals.decision, "pending"))); }
    const pendingPublicReports = await tx.select({ id: publicMarketReports.id }).from(publicMarketReports).where(and(eq(publicMarketReports.submittedBy, input.userId), eq(publicMarketReports.status, "pending"))); const publicReportIds = pendingPublicReports.map((row) => row.id); await tx.update(publicMarketReports).set({ quarantinedAt: now }).where(eq(publicMarketReports.submittedBy, input.userId)); if (publicReportIds.length) { await tx.update(publicMarketReports).set({ status: "rejected", reviewedBy: context.userId, reviewedAt: now, reviewNote: `Contributor quarantined: ${input.reason}` }).where(inArray(publicMarketReports.id, publicReportIds)); await tx.update(approvals).set({ decision: "rejected", reviewedBy: context.userId, reviewedAt: now, note: `Contributor quarantined: ${input.reason}` }).where(and(eq(approvals.targetType, "public_market_report"), inArray(approvals.targetId, publicReportIds), eq(approvals.decision, "pending"))); }
    const approvedReceiptIds = (await tx.select({ id: receipts.id }).from(receipts).where(and(eq(receipts.submittedBy, input.userId), eq(receipts.status, "approved")))).map((row) => row.id); await tx.update(users).set({ quarantinedAt: now, quarantineReason: input.reason, updatedAt: now }).where(eq(users.id, input.userId)); await tx.insert(jobs).values({ kind: "quarantine.recompute", payload: { userId: input.userId, excludedObservationIds: observationIds, excludedPublicMarketReportIds: publicReportIds, approvedReceiptIdsForReview: approvedReceiptIds } }); await tx.insert(auditEvents).values({ actorId: context.userId, action: "contributor.quarantined", entityType: "user", entityId: input.userId, after: { reason: input.reason, rejectedPendingReceipts: pendingIds.length, excludedObservations: observationIds.length, excludedPublicMarketReports: publicReportIds.length, approvedReceiptIdsForReview: approvedReceiptIds } }); return { action: input.action, rejectedReceipts: pendingIds.length, quarantinedObservations: observationIds.length, quarantinedPublicMarketReports: publicReportIds.length, approvedReceiptsFlaggedForReview: approvedReceiptIds.length }; }).catch((error: unknown) => ({ error: error instanceof Error ? error.message : "quarantine_failed" })); if ("error" in result) return NextResponse.json(result, { status: result.error === "user_not_found" ? 404 : 409 }); return NextResponse.json(result); }
