import { and, asc, eq, isNull } from "drizzle-orm";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/db/runtime";
import { auditEvents, memberships, users } from "@/db/schema";
import { mayManageStore } from "@/lib/authorization";
import { isStoreAccessFailure, selectStore } from "@/lib/services/store-access";
import { mayChangeMembership } from "@/lib/services/admin-policy";

const change = z.object({ userId: z.uuid(), role: z.enum(["clerk", "manager", "owner"]).optional(), trust: z.enum(["unverified", "verified"]).optional() }).refine((value) => value.role || value.trust, "Choose a role or trust update.");
async function manager(request: NextRequest) { const store = await selectStore(request); return isStoreAccessFailure(store) ? store : !mayManageStore(store.access) ? { status: 403 as const, error: "store_management_forbidden" } : store; }
export async function GET(request: NextRequest) { const store = await manager(request); if ("error" in store) return NextResponse.json({ error: store.error }, { status: store.status }); const rows = await db.select({ userId: users.id, name: users.name, discordId: users.discordId, quarantinedAt: users.quarantinedAt, role: memberships.role, trust: memberships.trust, displayName: memberships.displayName, joinedAt: memberships.joinedAt }).from(memberships).innerJoin(users, eq(memberships.userId, users.id)).where(and(eq(memberships.storeId, store.id), isNull(memberships.revokedAt))).orderBy(asc(users.name)); return NextResponse.json({ storeId: store.id, members: rows }); }
export async function PATCH(request: NextRequest) { const store = await manager(request); if ("error" in store) return NextResponse.json({ error: store.error }, { status: store.status }); const parsed = change.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "invalid_membership_update", issues: parsed.error.issues }, { status: 400 }); const [target] = await db.select({ role: memberships.role }).from(memberships).where(and(eq(memberships.storeId, store.id), eq(memberships.userId, parsed.data.userId), isNull(memberships.revokedAt))).limit(1); if (!target) return NextResponse.json({ error: "membership_not_found" }, { status: 404 }); if (!mayChangeMembership(store.access.role, target.role, parsed.data.role)) return NextResponse.json({ error: "owner_change_forbidden" }, { status: 403 }); const [updated] = await db.transaction(async (tx) => { const [row] = await tx.update(memberships).set(parsed.data).where(and(eq(memberships.storeId, store.id), eq(memberships.userId, parsed.data.userId))).returning(); await tx.insert(auditEvents).values({ actorId: store.context.userId, storeId: store.id, action: "membership.updated", entityType: "membership", after: { userId: parsed.data.userId, role: row.role, trust: row.trust } }); return [row]; }); return NextResponse.json({ membership: updated }); }
